//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CholibiClinic
{


    public partial class SiteMaster
    {

        /// <summary>
        /// HeadContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// plhAnonymous control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder plhAnonymous;

        /// <summary>
        /// plhLoggedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder plhLoggedIn;

        /// <summary>
        /// lblUserFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserFullName;

        /// <summary>
        /// lnkLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
    }
}
